application: static-webapp # cf. id de l'application acquise sur appengine.google.com
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

skip_files:
- ^\.git$